version: '3'

services:
  backend:
    build:
      context: ./server
    ports:
      - "8000:8000"
    depends_on:
      - database
    env_file:
      - .env

  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend

  database:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
